### ISSUE TITLE
When installing the extension for the first time, the settings default to "undefined".

### ISSUE THREAD

**Issue by Aydekins** [Aydekins/MathspaceMod#3]
When you install the extension for the first time, the settings will default to "undefined". So, when you load the page by default the greeting will say "undefined".

**Comment by CUZLOCKED-GD** [comment]
This bug is being worked on in the 0.0.6 update, and will be competely fixed in 0.0.7.

**Comment by Aydekins** [comment]
This bug has been fixed in the 0.0.7 update.
